[package]
name = "valine_bot"
version = "2.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.12.4"
# Git 上では修正されているが、crates.io にはまだ反映されていないため、git で指定
poise = { git = "https://github.com/serenity-rs/poise", rev = "db10b126c8b07f7e1924cba1672f04ff24ed4ec7" }
rand = "0.9"
regex = "1.0"
chrono = "0.4"
similar = "2.7"
dashmap = "6.1"
itertools = "0.14"
tracing = "0.1"
tracing-subscriber = "0.3"
serde_with = "3"
duration-str = "0.12"
toml = "0.8"
thiserror = "2"
async-stream = "0.3"
futures = "0.3"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "signal"] }
serde = { version = "1.0", features = ["derive"] }
bpaf = { version = "0.9", features = ["derive"] }

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true
codegen-units = 1
