
[bot]
token = "TOKEN"
application_id = "000000000000000000"
owners = ["000000000000000000"]


[auth]
# 認証の結果を通知するチャンネルID
log_channel_id = "000000000000000000"
# 認証後に付与するロールID
role_id = "000000000000000000"
# マッチしたら認証成功とする正規表現
trigger_regex = "[おオｵ][のノﾉ][れレﾚ][GgＧｇ][RrＲｒ][EeＥｅ][GgＧｇ]"
# オートコンプリートに表示されるダミーのキーワード
dummy_keywords = ["ダミー", "dummy"]


[message_logging]
# メッセージの削除・編集のログを残すチャンネルID
channel_id = "000000000000000000"


[message_cache]
# 過去メッセージのキャッシュを無効化するかどうか
disabled = false
# キャッシュする過去メッセージの最大数
limit = 1000
# 過去のメッセージのキャッシュを取るギルドIDのリスト
# target_guild_ids = ["651286346861641735"]
target_guild_ids = ["000000000000000000"]
# 過去メッセージのキャッシュ取らないチャンネルIDのリスト、親チャンネルを指定すると子のチャンネルも対象 (孫は対象外)
ignore_channel_ids = ["000000000000000000"]


[thread_channel_startup]
# 空にする方法
# threads = []

[[thread_channel_startup.threads]]
# 初期メッセージを投稿するスレッドチャンネルのID
channel_id = "000000000000000000"
# 初期メッセージの内容
startup_message = """スレッドの始まりだぁ！
まずはこのテンプレートを読んでね！"""

[thread_auto_invite]
# 自動で招待するロールのID
role_id = "000000000000000000"

[question]
# 質問の投稿先フォーラムのID
forum_id = "000000000000000000"
# 解決済みのタグID
solved_tag = "000000000000000000"
# 除外するタグIDのリスト
exclude_tags = ["000000000000000000"]
