[formatting]
column_width = 120
compact_arrays = false
compact_entries = false
compact_inline_tables = false
reorder_keys = false


[[rule]]
include = [ "**/Cargo.toml" ]
keys = [ "dependencies" ]


[rule.formatting]
reorder_keys = true
